version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - money_tracking-network

  backend:
    build:
      context: ./server        # üëà context ph·∫£i l√† th∆∞ m·ª•c g·ªëc
      dockerfile: Dockerfile  # üëà tr·ªè ƒë·∫øn ƒë√∫ng Dockerfile
    ports:
      - "5290:80"  # √Ånh x·∫° c·ªïng 5290 (theo launchSettings.json) t·ªõi c·ªïng 80 trong container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Ch·∫°y ·ªü m√¥i tr∆∞·ªùng Development ƒë·ªÉ b·∫≠t Swagger
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=money_tracking;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - money_tracking-network
    # volumes:
    #   - ./server:/app

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=money_tracking
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - money_tracking-network

volumes:
  postgres_data:

networks:
  money_tracking-network: